<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="B300LCOK" name="com.scripted.runners.SaveMartRunner" tests="3" failures="1" timestamp="2023-02-24T13:30:32 IST" time="161.534" errors="0">
  <testcase name="teardown" time="21.737" classname="com.scripted.runners.SaveMartRunner">
    <failure type="java.lang.AssertionError" message="Unable to Update the Test case and step statusorg.json.JSONException: JSONArray[1] not found.">
      <![CDATA[java.lang.AssertionError: Unable to Update the Test case and step statusorg.json.JSONException: JSONArray[1] not found.
at org.testng.Assert.fail(Assert.java:97)
at com.scripted.zephyr.ZephyrTestCaseManagementCloud.updateTestCaseAndStepStatus(ZephyrTestCaseManagementCloud.java:352)
at com.scripted.integration.JiraUtils.uploadResultsFromCucumberJson(JiraUtils.java:25)
at com.scripted.configurations.SkriptmateConfigurations.afterSuite(SkriptmateConfigurations.java:152)
at com.scripted.runners.SaveMartRunner.teardown(SaveMartRunner.java:25)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:63)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:348)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:302)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:351)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- teardown -->
  <system-out/>
  <testcase name="runScenario" time="63.647" classname="com.scripted.runners.SaveMartRunner"/>
  <system-out/>
  <testcase name="runScenario" time="76.150" classname="com.scripted.runners.SaveMartRunner"/>
  <system-out/>
</testsuite> <!-- com.scripted.runners.SaveMartRunner -->
